### ISSUE TITLE
New iOS Devices with 25 digit Udid is not supported

### ISSUE THREAD

**Issue by metalimangal** [AppiumTestDistribution/AppiumTestDistribution#683]
The new iOS Udid has 24 characters in udid, which is different from the 40 digits udid in previous iOS Phones.  

Verified in the ATD code, where we have only public final static int IOS_UDID_LENGTH = 40; as the ios udid variable mentioned for adding the iOS device, which doesn't run automation in the current iOS device.

**Comment by anandbagmar** [comment]
@metalimangal  - please share the class where you see the below: 
`public final static int IOS_UDID_LENGTH = 40;`

Also, share what version of ATD are you using

**Comment by saikrishna321** [comment]
This has been fixed! Can you please tell the ATD version?

**Comment by metalimangal** [comment]
Hi, This issue has been observed in 11.0.1 version of ATD. I have seen this in IOSDeviceConfiguration.java, also, IOS_UDID_LENGTH was being used for iOS and Android device validation in other files i.e. DeviceByHost.java, DesiredCapabilityBuilder.java and AndroidDeviceConfiguration.java

**Comment by chuklov** [comment]
That is exactly what my topic is about: https://github.com/AppiumTestDistribution/AppiumTestDistribution/issues/657

No one fix it and it still doesn't work.
